# Generated by Django 5.1.5 on 2025-02-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI'), ('cod', 'Cash on Delivery')], default='cod', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method_details',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('processing', 'Processing'), ('refunded', 'Refunded')], default='processing', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
