# Generated by Django 5.1.5 on 2025-02-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_status_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
