# Generated by Django 5.1.5 on 2025-02-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
