# Generated by Django 5.1.5 on 2025-02-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productvariant_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
    ]
