# Generated by Django 5.1.5 on 2025-02-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productimage_delete_productvariantimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(default='tags/default.jpg', upload_to='tags/'),
        ),
    ]
