# Generated by Django 5.1.5 on 2025-02-08 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_tag_is_active_tag_on_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(limit_choices_to={'category': models.F('category')}, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
    ]
