# Generated by Django 5.1.5 on 2025-02-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='color',
            field=models.CharField(default='dark', max_length=255),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='attributes',
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.CharField(default='dark', max_length=255),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(default='M', max_length=128),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
    ]
