# Generated by Django 5.1.5 on 2025-02-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_coupon_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(default='', help_text='Enter each feature on a new line.'),
        ),
        migrations.AddField(
            model_name='product',
            name='materials_care',
            field=models.TextField(default='', help_text='Enter each material/care instruction on a new line.'),
        ),
    ]
