# Generated by Django 5.1.5 on 2025-02-22 12:18

import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='category', chained_model_field='category', default=None, horizontal=True, related_name='tag', to='product.tag', verbose_name='tag'),
        ),
    ]
