# Generated by Django 5.1.5 on 2025-02-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('store_address', models.CharField(max_length=512)),
                ('store_city', models.CharField(max_length=512)),
                ('store_state', models.CharField(max_length=512)),
                ('store_country', models.CharField(max_length=512)),
                ('store_zip_code', models.CharField(max_length=512)),
                ('store_email', models.EmailField(max_length=254)),
                ('store_phone', models.CharField(max_length=512)),
                ('store_timings', models.CharField(max_length=512)),
                ('store_image', models.ImageField(upload_to='stores/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
