# Generated by Django 5.1.5 on 2025-02-22 15:31

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_date'),
        ('users', '0003_useraddress_address_nickname_useraddress_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='user', on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='users.useraddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='user', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='users.useraddress'),
        ),
    ]
