# Generated by Django 5.1.5 on 2025-02-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('sub_title', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='banners/')),
                ('tags', models.CharField(default='Trending', max_length=512)),
                ('button_text', models.CharField(max_length=512)),
            ],
        ),
    ]
