# Generated by Django 5.1.5 on 2025-02-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='tags',
            new_name='tag',
        ),
    ]
