# Generated by Django 5.1.5 on 2025-02-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_featuredproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
