# Generated by Django 5.1.5 on 2025-02-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_banner_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('sub_title', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='mid_banners/')),
                ('tag', models.CharField(default='Trending', max_length=512)),
                ('button_text', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
