# Generated by Django 5.1.5 on 2025-02-08 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_midbanner'),
        ('product', '0015_alter_tag_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('sub_title', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='men-banners/')),
                ('button_text', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_banners', to='product.tag')),
            ],
        ),
        migrations.CreateModel(
            name='WomenBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('sub_title', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='women-banners/')),
                ('button_text', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='women_banners', to='product.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AlterField(
            model_name='collection',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='product.tag'),
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_products', to='product.tag'),
        ),
        migrations.AlterField(
            model_name='midbanner',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mid_banners', to='product.tag'),
        ),
    ]
