# Generated by Django 5.1.5 on 2025-02-08 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_menbanner_womenbanner_delete_banner_and_more'),
        ('product', '0015_alter_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menbanner',
            name='tag',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Men'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_banners', to='product.tag'),
        ),
        migrations.AlterField(
            model_name='womenbanner',
            name='tag',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Women'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='women_banners', to='product.tag'),
        ),
    ]
