# Generated by Django 5.1.5 on 2025-02-08 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0008_alter_menbanner_tag_alter_womenbanner_tag'),
        ('product', '0015_alter_tag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredproduct',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='midbanner',
            name='tag',
        ),
        migrations.CreateModel(
            name='MenCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='collections/')),
                ('button_text', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Men'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_collections', to='product.tag')),
            ],
        ),
        migrations.CreateModel(
            name='MenFeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('sub_title', models.CharField(max_length=512)),
                ('quote_text', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='featured_products/')),
                ('button_text', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Men'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_featured_products', to='product.tag')),
            ],
        ),
        migrations.CreateModel(
            name='MenMidBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('sub_title', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='mid_banners/')),
                ('button_text', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Men'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_mid_banners', to='product.tag')),
            ],
        ),
        migrations.CreateModel(
            name='WomenCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='collections/')),
                ('button_text', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Women'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='women_collections', to='product.tag')),
            ],
        ),
        migrations.CreateModel(
            name='WomenFeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('sub_title', models.CharField(max_length=512)),
                ('quote_text', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='featured_products/')),
                ('button_text', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Women'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='women_featured_products', to='product.tag')),
            ],
        ),
        migrations.CreateModel(
            name='WomenMidBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('sub_title', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='mid_banners/')),
                ('button_text', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Women'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='women_mid_banners', to='product.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
        migrations.DeleteModel(
            name='MidBanner',
        ),
    ]
