# Generated by Django 5.1.5 on 2025-02-08 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0009_remove_featuredproduct_tag_remove_midbanner_tag_and_more'),
        ('product', '0016_tag_is_active_tag_on_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menbanner',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='menbanner',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='menbanner',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='menbanner',
            name='title',
        ),
        migrations.AddField(
            model_name='menbanner',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_banners', to='product.productvariant'),
        ),
        migrations.CreateModel(
            name='KidsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('sub_title', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='kids-banners/')),
                ('button_text', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Kids'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids_banners', to='product.tag')),
            ],
        ),
        migrations.CreateModel(
            name='KidsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='collections/')),
                ('button_text', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Kids'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids_collections', to='product.tag')),
            ],
        ),
        migrations.CreateModel(
            name='KidsFeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('sub_title', models.CharField(max_length=512)),
                ('quote_text', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='featured_products/')),
                ('button_text', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Kids'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids_featured_products', to='product.tag')),
            ],
        ),
        migrations.CreateModel(
            name='KidsMidBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('sub_title', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='mid_banners/')),
                ('button_text', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Kids'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids_mid_banners', to='product.tag')),
            ],
        ),
    ]
