# Generated by Django 5.1.5 on 2025-02-08 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0010_remove_menbanner_button_text_and_more'),
        ('product', '0018_alter_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenCountdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('sub_title', models.CharField(max_length=512)),
                ('button_text', models.CharField(max_length=512)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='menbanner',
            name='product_variant',
            field=models.ForeignKey(blank=True, limit_choices_to={'product__category__name': 'Men'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_banners', to='product.productvariant'),
        ),
    ]
