# Generated by Django 5.1.5 on 2025-02-09 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0011_mencountdown_alter_menbanner_product_variant'),
        ('product', '0018_alter_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mencollection',
            name='sub_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Men'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_collections', to='product.subcategory'),
        ),
    ]
