# Generated by Django 5.1.5 on 2025-02-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0012_mencollection_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mencollection',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='mencollection',
            name='tag',
        ),
    ]
