# Generated by Django 5.1.5 on 2025-02-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0013_remove_mencollection_button_text_and_more'),
        ('product', '0018_alter_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mencountdown',
            name='image',
            field=models.ImageField(default='countdown/default.jpg', upload_to='countdown/'),
        ),
        migrations.AddField(
            model_name='mencountdown',
            name='tag',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name': 'Men'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_countdown', to='product.tag'),
        ),
    ]
