# Generated by Django 5.1.5 on 2025-02-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0014_mencountdown_image_mencountdown_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenBarText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
