# Generated by Django 5.1.5 on 2025-02-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0015_menbartext'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidscollection',
            name='sub_title',
            field=models.CharField(default='', max_length=512),
        ),
    ]
