# Generated by Django 5.1.5 on 2025-02-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0016_kidscollection_sub_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidBarText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='KidsFeaturedProduct',
        ),
    ]
